# frozen_string_literal: true

# Currently doesn't work with Appraisal 2.5.0 and Ruby >= 3.2
# customize_gemfiles do
#   {
#     heading: <<~HEADING
#       # frozen_string_literal: true
#
#       `%<gemfile>s` has been generated by Appraisal, do NOT modify it or `%<lockfile>s` directly!
#       Make the changes to the "%<appraisal>s" block in `Appraisals` instead.
#     HEADING
#   }
# end

appraise "bigdecimal3" do
  gem "bigdecimal", "~> 3.1"
end

appraise "bigdecimal4" do
  gem "bigdecimal", "~> 4.0"
end
